# Generated by Django 2.2.8 on 2020-08-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendees',
            options={'verbose_name_plural': 'Attendees'},
        ),
    ]
