# Generated by Django 2.2.8 on 2020-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_on', models.IntegerField()),
                ('part_number', models.CharField(default='', max_length=150)),
                ('part_name', models.CharField(default='', max_length=150)),
                ('supplier_code', models.CharField(default='', max_length=150)),
                ('project_code', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
