# Generated by Django 2.2.8 on 2020-08-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partMaster', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartMaster',
            new_name='Part_master',
        ),
    ]
