# Generated by Django 2.2.8 on 2020-11-24 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_no', models.CharField(blank=True, max_length=150, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 12, 17, 14, 22992))),
                ('route_code', models.CharField(blank=True, max_length=150, null=True)),
                ('route_trip', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('truckplan_no', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 5, 17, 14, 22992), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TruckPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckplan_no', models.CharField(blank=True, max_length=150, null=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('route_code', models.CharField(blank=True, max_length=150, null=True)),
                ('route_trip', models.CharField(blank=True, max_length=5, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 5, 17, 14, 24005), null=True)),
            ],
        ),
    ]
