# Generated by Django 2.2.8 on 2020-11-24 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 12, 17, 55, 487835)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 5, 17, 55, 487835), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 24, 5, 17, 55, 488834), null=True),
        ),
    ]
