# Generated by Django 2.2.8 on 2020-09-29 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 29, 7, 3, 27, 396072), null=True),
        ),
    ]
