# Generated by Django 2.2.8 on 2020-11-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0002_auto_20201124_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 14, 1, 38, 781481)),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 7, 1, 38, 781481), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 14, 1, 38, 781481)),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 26, 7, 1, 38, 781481), null=True),
        ),
    ]
