# Generated by Django 2.2.8 on 2020-09-29 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0002_auto_20200929_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='order_count',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 29, 7, 3, 33, 83912), null=True),
        ),
    ]
