# Generated by Django 2.2.8 on 2020-10-01 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0003_auto_20200929_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickup',
            old_name='trip_no',
            new_name='route_trip',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 1, 9, 30, 55, 81749), null=True),
        ),
    ]
