# Generated by Django 2.2.8 on 2020-10-01 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0004_auto_20201001_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 1, 9, 35, 52, 30846), null=True),
        ),
    ]
