# Generated by Django 2.2.8 on 2020-10-06 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0005_auto_20201001_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 6, 10, 14, 33, 818076), null=True),
        ),
    ]
