# Generated by Django 2.2.8 on 2020-10-09 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0008_auto_20201009_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='truckPlan_no',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 6, 52, 155789), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 6, 52, 155789), null=True),
        ),
    ]
