# Generated by Django 2.2.8 on 2020-10-09 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0009_auto_20201009_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickup',
            name='truckPlan_no',
        ),
        migrations.AddField(
            model_name='pickup',
            name='truckplan_no',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 8, 56, 427020), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 8, 56, 427020), null=True),
        ),
    ]
