# Generated by Django 2.2.8 on 2020-10-09 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0010_auto_20201009_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckplan',
            old_name='truckPlan_no',
            new_name='truckplan_no',
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 12, 15, 929548), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 9, 5, 12, 15, 930549), null=True),
        ),
    ]
