# Generated by Django 2.2.8 on 2020-10-20 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_plan_management', '0011_auto_20201009_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckplan',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 8, 22, 54, 316545), null=True),
        ),
        migrations.AlterField(
            model_name='truckplan',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 20, 8, 22, 54, 317460), null=True),
        ),
    ]
