# Generated by Django 2.2.8 on 2020-08-11 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 0, 9, 34, 189404)),
        ),
        migrations.AlterField(
            model_name='project',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 0, 9, 34, 189404)),
        ),
    ]
