# Generated by Django 2.2.8 on 2020-08-12 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200812_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 11, 31, 13, 81588)),
        ),
        migrations.AlterField(
            model_name='project',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 11, 31, 13, 81588)),
        ),
    ]
