# Generated by Django 2.2.8 on 2020-08-12 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200812_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='effective_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 12, 7, 44, 546261)),
        ),
        migrations.AlterField(
            model_name='project',
            name='expire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 12, 7, 44, 546261)),
        ),
    ]
