# Generated by Django 2.2.8 on 2020-09-14 07:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_code', models.CharField(blank=True, max_length=150, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('is_working', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('updated_by', models.CharField(default='', max_length=150)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(blank=True, max_length=150, null=True)),
                ('package_no', models.CharField(blank=True, max_length=150, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('station_code', models.CharField(blank=True, max_length=150, null=True)),
                ('image_url', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=150, null=True)),
                ('part_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('snp', models.IntegerField(blank=True, default=0, null=True)),
                ('part_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=150, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('package_no', models.CharField(blank=True, max_length=50, null=True)),
                ('package_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_code', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('remark', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('updated_by', models.CharField(default='', max_length=150)),
                ('updated_date', models.DateTimeField()),
                ('customer_code', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=150, null=True)),
                ('route_code', models.CharField(blank=True, max_length=150, null=True)),
                ('trip_no', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_license', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_code', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route_no', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouterMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_no', models.CharField(blank=True, max_length=250, null=True)),
                ('route_code', models.CharField(blank=True, max_length=150, null=True)),
                ('trip_no', models.CharField(blank=True, max_length=5, null=True)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pickup_before', models.IntegerField(blank=True, null=True)),
                ('release_time', models.CharField(blank=True, max_length=15, null=True)),
                ('pickup_time', models.CharField(blank=True, max_length=15, null=True)),
                ('depart_time', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=15, null=True)),
                ('complete_time', models.CharField(blank=True, max_length=15, null=True)),
                ('transporter', models.CharField(blank=True, max_length=50, null=True)),
                ('project_code', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=15, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 14, 7, 54, 13, 299942, tzinfo=utc), null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(default='', max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('station_type', models.CharField(blank=True, max_length=250, null=True)),
                ('zone', models.CharField(blank=True, max_length=250, null=True)),
                ('province', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=350, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('project_code', models.CharField(default='', max_length=150)),
                ('updated_by', models.CharField(default='', max_length=150)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_license', models.CharField(max_length=250)),
                ('province', models.CharField(blank=True, max_length=250, null=True)),
                ('truck_type', models.CharField(blank=True, max_length=250, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=250, null=True)),
                ('max_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
