# Generated by Django 2.2.8 on 2020-11-21 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routermaster',
            old_name='trip_no',
            new_name='route_trip',
        ),
        migrations.AddField(
            model_name='package',
            name='snp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='package_volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='package_weight',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='routermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 7, 27, 30, 919956, tzinfo=utc), null=True),
        ),
    ]
