# Generated by Django 2.2.8 on 2020-09-21 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='snp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 21, 6, 29, 44, 66434, tzinfo=utc), null=True),
        ),
    ]
