# Generated by Django 2.2.8 on 2020-10-30 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_auto_20200921_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routermaster',
            old_name='trip_no',
            new_name='route_trip',
        ),
        migrations.AlterField(
            model_name='routermaster',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 3, 13, 56, 76366, tzinfo=utc), null=True),
        ),
    ]
