# Generated by Django 2.2.8 on 2020-08-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField()),
                ('part_number', models.CharField(default='', max_length=150)),
                ('supplier_name', models.CharField(default='', max_length=150)),
                ('plant', models.CharField(default='', max_length=150)),
                ('order_amount', models.IntegerField(blank=True, null=True)),
                ('order_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 15, 41, 42, 38521))),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
