# Generated by Django 2.2.8 on 2020-08-12 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 16, 31, 14, 554493)),
        ),
    ]
