# Generated by Django 2.2.8 on 2020-11-23 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('file_size', models.CharField(blank=True, max_length=150, null=True)),
                ('order_count', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('customer_code', models.CharField(default='', max_length=50)),
                ('project_code', models.CharField(default='', max_length=50)),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 23, 14, 55, 2, 610624))),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='plant',
            new_name='file_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='supplier_name',
            new_name='order_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 23, 7, 55, 2, 611622, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 23, 14, 55, 2, 610624)),
        ),
        migrations.AddField(
            model_name='order',
            name='history_updated',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='is_part_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_route_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_no',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='package_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_no',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='plant_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='project_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='route_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='route_trip',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
