# Generated by Django 2.2.8 on 2020-08-12 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200812_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_no',
            new_name='order_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 16, 32, 18, 104981)),
        ),
    ]
