# Generated by Django 2.2.8 on 2020-08-13 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200813_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 11, 11, 57, 853308)),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 11, 11, 57, 853308)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 11, 11, 57, 853308)),
        ),
    ]
