# Generated by Django 2.2.8 on 2020-08-13 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200813_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_no',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 12, 10, 34, 855947)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 12, 10, 34, 855947)),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 13, 12, 10, 34, 855947)),
        ),
    ]
