# Generated by Django 2.2.8 on 2020-08-15 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200815_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_master',
            old_name='package_no',
            new_name='plant_code',
        ),
        migrations.RenameField(
            model_name='part_master',
            old_name='part_name',
            new_name='route_code',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='part_weight',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='snp',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='uploaded_datetime',
        ),
        migrations.AddField(
            model_name='part_master',
            name='release_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 5, 791244)),
        ),
        migrations.AddField(
            model_name='part_master',
            name='trip_no',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 5, 787964)),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 5, 787964)),
        ),
    ]
