# Generated by Django 2.2.8 on 2020-08-15 04:45

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200815_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='router_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('route_code', models.CharField(default='', max_length=150)),
                ('trip_no', models.CharField(default='', max_length=5)),
                ('supplier_code', models.CharField(default='', max_length=50)),
                ('plant_code', models.CharField(default='', max_length=50)),
                ('release_datetime', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 47, 649398))),
                ('pickup_datetime', models.DateTimeField(blank=True)),
                ('depart_datetime', models.DateTimeField(blank=True)),
                ('delivery_datetime', models.DateTimeField(blank=True)),
                ('complete_datetime', models.DateTimeField(blank=True)),
                ('transporter', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='part_master',
            old_name='plant_code',
            new_name='package_no',
        ),
        migrations.RenameField(
            model_name='part_master',
            old_name='route_code',
            new_name='part_name',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='release_datetime',
        ),
        migrations.RemoveField(
            model_name='part_master',
            name='trip_no',
        ),
        migrations.AddField(
            model_name='part_master',
            name='part_number',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='part_master',
            name='part_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='part_master',
            name='project_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='part_master',
            name='remark',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='part_master',
            name='service_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='part_master',
            name='snp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part_master',
            name='updated_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='part_master',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 47, 649398)),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 47, 648383)),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 11, 45, 47, 648383)),
        ),
    ]
