# Generated by Django 2.2.8 on 2020-08-15 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200815_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 13, 756972), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 13, 756972)),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 13, 756972)),
        ),
    ]
