# Generated by Django 2.2.8 on 2020-08-15 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20200815_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 21, 256031), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 21, 256031)),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 22, 47, 21, 256031)),
        ),
    ]
