# Generated by Django 2.2.8 on 2020-08-15 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200815_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_part_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_route_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 23, 2, 1, 978131), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 23, 2, 1, 978131)),
        ),
        migrations.AlterField(
            model_name='order',
            name='uploaded_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 15, 23, 2, 1, 978131)),
        ),
    ]
