# Generated by Django 2.2.8 on 2020-08-16 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200815_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uploaded_datetime',
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 15, 20, 12, 332046), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 16, 15, 20, 12, 332046)),
        ),
    ]
