# Generated by Django 2.2.8 on 2020-08-17 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_auto_20200817_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 11, 16, 10, 487940), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 17, 11, 16, 10, 487940)),
        ),
        migrations.AlterField(
            model_name='order',
            name='route_trip',
            field=models.CharField(default='', max_length=150),
        ),
    ]
