# Generated by Django 2.2.8 on 2020-08-18 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20200817_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Item_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 12, 52, 43, 310536), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 12, 52, 43, 310536)),
        ),
    ]
