# Generated by Django 2.2.8 on 2020-08-18 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_auto_20200818_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_active',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='order',
            name='history_updated',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 18, 4, 43, 180305), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 18, 4, 43, 179303)),
        ),
    ]
