# Generated by Django 2.2.8 on 2020-08-18 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_auto_20200818_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_actived',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 19, 25, 42, 139292), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 19, 25, 42, 139292)),
        ),
    ]
