# Generated by Django 2.2.8 on 2020-08-18 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_auto_20200818_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 22, 5, 46, 763900), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 22, 5, 46, 763900)),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_part_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_route_completed',
            field=models.BooleanField(default=False),
        ),
    ]
