# Generated by Django 2.2.8 on 2020-10-02 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_auto_20200904_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_no',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 5, 27, 27, 52888, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 2, 12, 27, 27, 52888)),
        ),
    ]
