# Generated by Django 2.2.8 on 2020-10-27 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_auto_20201002_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('file_name', models.CharField(blank=True, max_length=150, null=True)),
                ('file_size', models.CharField(blank=True, max_length=150, null=True)),
                ('order_count', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(default='', max_length=50)),
                ('project_id', models.CharField(default='', max_length=50)),
                ('created_by', models.CharField(default='', max_length=15)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 10, 27, 11, 46, 54, 236905))),
                ('updated_by', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 11, 46, 54, 236905))),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Item_no',
            new_name='item_no',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 4, 46, 54, 237905, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 11, 46, 54, 236905)),
        ),
    ]
