# Generated by Django 2.2.8 on 2020-10-27 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_auto_20201027_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 12, 25, 37, 614297)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 5, 25, 37, 615298, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 27, 12, 25, 37, 615298)),
        ),
    ]
