# Generated by Django 2.2.8 on 2020-10-30 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_auto_20201027_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='file_id',
            new_name='file_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='order_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='plant_code',
            new_name='plant_code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='supplier_code',
            new_name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_updated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='trip_no',
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 9, 52, 30, 857064)),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 2, 52, 30, 857064, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 9, 52, 30, 857064)),
        ),
    ]
