# Generated by Django 2.2.8 on 2020-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_no',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
