# Generated by Django 2.2.8 on 2020-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20200811_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
