# Generated by Django 2.2.8 on 2020-08-12 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_file_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 11, 31, 13, 89590)),
        ),
        migrations.AddField(
            model_name='file',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 11, 31, 13, 89590)),
        ),
    ]
