# Generated by Django 2.2.8 on 2020-08-12 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20200812_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='order_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 11, 35, 38, 4127)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 11, 35, 38, 4127)),
        ),
    ]
