# Generated by Django 2.2.8 on 2020-08-12 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20200812_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 12, 7, 44, 550273)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 12, 12, 7, 44, 550273)),
        ),
    ]
