# Generated by Django 2.2.8 on 2020-08-18 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_auto_20200812_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 18, 33, 46, 849354)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 18, 33, 46, 849354)),
        ),
    ]
