# Generated by Django 2.2.8 on 2020-08-18 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0010_auto_20200818_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 18, 34, 35, 17386)),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 18, 34, 35, 17386)),
        ),
    ]
