# Generated by Django 2.2.8 on 2020-08-23 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0011_auto_20200818_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 15, 32, 31, 418973)),
        ),
        migrations.AlterField(
            model_name='file',
            name='customer_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='project_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 23, 15, 32, 31, 418973)),
        ),
    ]
