# Generated by Django 2.2.8 on 2020-08-27 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0013_auto_20200825_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 15, 0, 48, 630095)),
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 27, 15, 0, 48, 630095)),
        ),
    ]
